@base_url = http://localhost:6000
@actk = {{login.response.body.token}}

###
GET {{base_url}} HTTP/1.1

######### login
# @name login
POST {{base_url}}/users/login HTTP/1.1
Content-Type: application/json

{
    "username" : "a",
    "password" : "11234567"
}

###### get invoice
GET  {{base_url}}/get/invoice HTTP/1.1
Content-Type: application/json
actk: {{actk}}

### get invioce_detail
GET {{base_url}}/get/invoice_detail/IN10014 HTTP/1.1
Content-Type: application/json
actk: {{actk}}

### update status 
PUT {{base_url}}/update_status/invoice HTTP/1.1
Content-Type: application/json
actk: {{actk}}

{
    "invid" : "IN10014"
}

